name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    name: Vim Table Mode Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: pack/plugins/start/vim-table-mode

      - name: Checkout vim-testify
        uses: actions/checkout@v3
        with:
          repository: dhruvasagar/vim-testify
          path: pack/plugins/start/vim-testify

      - name: Install Vim or neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: Run unit tests
        env:
          VIM: ${{ steps.vim.outputs.executable }}
        run: |
          cd ${{ github.workspace }}/pack/plugins/start/vim-table-mode
          echo "set packpath+=${{ github.workspace }}" > vimrc
          ${VIM} --headless -u vimrc +TestifySuite +qall
