name: CI

on:
  push:
    branches:
      - master
      - feature/switch-to-vim-testify
  pull_request:
    branches:
      - master
      - feature/switch-to-vim-testify

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Vim Table Mode Tests
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Install git & vim
        run: apk --no-cache add git vim

      - uses: actions/checkout@v3
        with:
          path: ~/.vim/pack/plugins/start/vim-table-mode

      - name: Checkout vim-testify
        uses: actions/checkout@v3
        with:
          repository: dhruvasagar/vim-testify
          path: ~/.vim/pack/plugins/start/vim-testify

      - name: Run unit tests
        run: |
          cd ~/.vim/pack/plugins/start/vim-table-mode
          vim +TestifySuite
