name: CI

on:
  push:
    branches:
      - master
      - feature/switch-to-vim-testify
  pull_request:
    branches:
      - master
      - feature/switch-to-vim-testify

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Vim Table Mode Tests
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Install vim
        run: apk --no-cache add vim

      - uses: actions/checkout@v3

      - name: Checkout vim-testify
        uses: actions/checkout@v3
        with:
          repository: dhruvasagar/vim-testify
          path: vim-testify

      - name: Run unit tests
        run: vim +"set packpath+=${{ github.workspace }}/vim-table-mode,${{ github.workspace }}/vim-testify" +TestifySuite
